[General]
; Show debug console.
Console = false
; Skips intro videos.
SkipIntro = true

[Fixes]
; Fixes firstborn syndrome and other uninitialized random seeds.
FixRNG = true
; Fixes OFB employees having default faces when changing their uniform. Requires the "ld_TS2Extender_uniformFix.package" file to be in your "Documents/The Sims 2/Downloads" folder in order to work.
FixOFBUniform = true
; Fixes a Maxis oversight that causes pink flashing due to Large Address Aware. Thanks to @spockthewok on GitHub for discovering this.
FixPinkFlashing = true

[Advanced]
; Adds a whole lot of new Lua features and restores sandboxed functionality. Plus makes print() log to the debug console. Check https://lazyduchess.github.io/TS2-Extender-Docs/ for documentation.
ExtendedLua = true

[Enhancements]
; Allows choosing separates (tops, bottoms, outfits) in CAS on all clothing categories.
Separates4All = false